package com.tigrisdata.db.annotation;

import com.tigrisdata.db.type.AutoGeneratedFields;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/** Specifies a field of a document. Allows user to customize the schema for the field. */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD})
public @interface TigrisField {
  /**
   * Description of the field, this is for documentation / readability purpose
   *
   * @return description string
   */
  String description() default "";

  /**
   * Tigris server auto-generates primary key if user's schema does not specify that. At later point
   * if user wants to map those auto generated keys to their Java model, they can either add a new
   * field with name exactly as `_id` and type {@link java.util.UUID}. Alternatively if you want to
   * add a field name that isn't `_id` you can use this annotation on top of the field of your
   * choice. Note: just the field type still has to be {@link java.util.UUID}
   *
   * @return field mapping
   */
  AutoGeneratedFields autoGeneratedFieldMapping() default AutoGeneratedFields.NONE;
}
