package com.tigrisdata.db.type;

public enum AutoGeneratedFields {
  ID("id"),
  NONE("");
  private final String fieldName;

  AutoGeneratedFields(String fieldName) {
    this.fieldName = fieldName;
  }

  public String getFieldName() {
    return fieldName;
  }
}
