name: java-ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH deploy keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.API_DEPLOY_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        id: mvn-tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.5.0
        id: jacoco
        with:
          generate-branches-badge: true
          jacoco-csv-file: client/target/site/jacoco/jacoco.csv
          on-missing-report: fail
          generate-summary: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./client/target/site/jacoco/jacoco.xml
